name: analytics_app
description: "A Flutter-based business analytics app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.5.1
  firebase_storage: ^12.3.2
  provider: ^6.1.2
  fl_chart: ^0.70.0
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  pdf: ^3.10.8
  printing: ^5.11.1
  excel: ^4.0.6
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"
  adaptive_icon_background: "#4FC3F7"
  adaptive_icon_foreground: "assets/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/
